### PR TITLE
Add differential_expression as step in the plan

### PR DESCRIPTION
**Pull request by kelshmo**
This builds upon PR #147. 

- Differentiates the conditions to make gene filtering more or less permissive (`conditions` in `rnaseq_plan`) from the differences between groups that will be applied to differential expression analysis(`de_contrasts` in `rnaseq_plan`). There are cases where these values would differ therefore, this change makes the workflow more flexible.
- Adds a cleaning step in `stepwise_regression` to return variables that map exactly to column names in the metadata. The formula passed to `differential_expression` may need to be modified (e.g. variables removed based on the contrast). Though not yet fully implemented, it is easier to subset these significant covariates when they are passed to `differential_expression`, as this function accepts variables to exclude. 
- Adds `wrap_de` to the plan. The significant covariates identified in the step of the plan called `model` are passed to `wrap_de`. `wrap_de` accepts lists of conditions and will return top-ranked gene lists.

### CODE REVIEW

**Review by jgockley62 — CHANGES_REQUESTED** [review]
Minor: 
     A) Each `variancePartition::dream()`call outputs the warning: `'package:stats' may not be available when loading'package:stats'` repetitively, does stats need to be added in the function header with `@importFrom` ?
     
     B) Direction of effect value uses adjusted p-value of 0.5 not 0.05 [Line 549](https://github.com/Sage-Bionetworks/sageseqr/blob/a22be096cbbd8d693a45508eebeda32010064c05/R/functions.R#L549)

Major: 
    Only runs if:
    A) [Line 509
](https://github.com/Sage-Bionetworks/sageseqr/blob/a22be096cbbd8d693a45508eebeda32010064c05/R/functions.R#L509)
        is changed to: `voom_gene_expression$E <- cqn_counts$E`
     
      B) [Line 536
](https://github.com/Sage-Bionetworks/sageseqr/blob/a22be096cbbd8d693a45508eebeda32010064c05/R/functions.R#L536)
        is changed to: `fit_contrasts = variancePartition::dream(exprObj = voom_gene_expression$E, 
        formula = metadata_input$formula_non_intercept, data = metadata_input$metadata, 
        L = contrasts)`

**Comment by kelshmo** [comment]
A.) That is a problem with how imports are declared in `variancePartition`. I am not able to reproduce - I suggest opening an issue with that package. 
B.) That was definitely a typo. I fixed by making that a mutable argument `de p-value threshold`.

A.) Instead of changing the function. I opted to change the `plan`. My assumption is that someone would pass a data frame and not a list object to the function. See [here](https://github.com/Sage-Bionetworks/sageseqr/pull/148/files#diff-9577ca60031235e72be43c0491b5bfd9f7fd3f6a8a8483592863f20230edf2c7R103). 
B.) `dream` is meant to accept a formal class `EList` object which is what `voom_gene_expression` is; did you run into an error?

**Comment by jgockley62** [comment]
[Line 536](https://github.com/Sage-Bionetworks/sageseqr/blob/a22be096cbbd8d693a45508eebeda32010064c05/R/functions.R#L536)

variancePartition::dream argument exprObj takes a matrix object. voom_gene_expression is a list/voom object. voom_gene_expression$E or voom_gene_expression$counts works though.

**Comment by kelshmo** [comment]
The documentation for `dream` `exprObj` is: 
>matrix of expression data (g genes x n samples), or ExpressionSet, or EList returned by voom() from the limma package

**Comment by jgockley62** [comment]
Weird Here's the error I get with using an EList versus using the matrix of counts:
`
class(voom_gene_expression)
  _[1] "EList"
  attr(,"package")
  [1] "limma"_
fit_contrasts = variancePartition::dream(exprObj = voom_gene_expression, formula = metadata_input$formula_non_intercept, data = metadata_input$metadata, L = contrasts)
  _Error in variancePartition::dream(exprObj = voom_gene_expression, formula = 
  metadata_input$formula_non_intercept,  : 
    exprObj and weightsMatrix must be the same dimensions_

class(voom_gene_expression$E)
  _[1] "matrix" "array"_ 
fit_contrasts = variancePartition::dream(exprObj = voom_gene_expression$E, 
        formula = metadata_input$formula_non_intercept, data = metadata_input$metadata, 
        L = contrasts)
  _Dividing work into 112 chunks...
  'package:stats' may not be available when loading...._

**Comment by kelshmo** [comment]
Note that #149 still blocks customization of the model. In this PR, the stepwise regression model is supplied to determine differential expression results without modification.

**Review by jgockley62 — APPROVED** [review]
This will error out if the biomart object doesn't have all the features annotated with it. The cqn_counts object will omit those features and the DE variance partition will error out because the filtered counts and cqn_counts have different dimentions

**Comment by jgockley62** [comment]
Also, thought for later. A contrast filter if some one wants to look at a tissue x diagnoisis x sex comparison the resulting number of contrasts is going to be extensive. Where they may just want AD Vs Control in males and females for each tissue.

**Comment by kelshmo** [comment]
Merging this PR to gain the complete suite of differential expression analysis functionality. The plan is being deprecated as is documented in PR #154 so incorporating differential expression into the workflow will get completed there.

**Pull request merged**
