### PR TITLE
Targets migration

### PR DESCRIPTION
**Pull request by jgockley62**
@kelshmo I should've amended and migrated over all the documentation. The main example default config.yaml works. There's a new paradigm compared to drake. The RNASeq_plan() function has been eliminated. In it's place a base _targets.R file calls the arguments from the config.yaml file. I wasn't able to figure out how to pass the config arguments into a function and then into nested targets options. That didn't work for me for some reason.

The new run basically copies the template_targets.R file, pastes the use config profile term into the targets file and creates a new_targets.R file in the main directory of the package. then `targets::tar_manifest` builds the 'plan' and `targets::tar_make()` runs the 'plan'.

### CODE REVIEW

**Comment by kelshmo** [comment]
Fixes #121.

**Comment by kelshmo** [comment]
@jgockley62, the workflow written in targets is fully functional in the PR. Can you also please test this PR? It includes our first major version release, [suggesting package stability](https://semver.org/#spec-item-5)!

**Comment by jgockley62** [comment]
@kelshmo This works great through the model. DE module is a little weird though. `cqn$E` Has a different number of counts than `filtered_counts` We can work this out in post though. Would roll these changes in!

**Comment by kelshmo** [comment]
I fixed the failing build after much trial and error 🥇

**Comment by jgockley62** [comment]
@kelshmo  Whoooooo!

**Comment by jgockley62** [comment]
@kelshmo Are we ready to merge this to master?

**Comment by kelshmo** [comment]
Tested on real data to confirm everything is functioning!

**Pull request merged**
